"""Add case law tables (docket, opinion_cluster, citation, parenthetical)

Revision ID: 92dbfcfed916
Revises: dd4c263ddf70
Create Date: 2025-11-11 16:55:56.318934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dbfcfed916'
down_revision = 'dd4c263ddf70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_opinionscited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_opinion_id', sa.Integer(), nullable=False),
    sa.Column('cited_opinion_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_opinionscited_cited_opinion_id'), 'search_opinionscited', ['cited_opinion_id'], unique=False)
    op.create_index(op.f('ix_search_opinionscited_citing_opinion_id'), 'search_opinionscited', ['citing_opinion_id'], unique=False)
    op.create_index(op.f('ix_search_opinionscited_id'), 'search_opinionscited', ['id'], unique=False)
    op.create_table('search_parenthetical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('described_opinion_id', sa.Integer(), nullable=False),
    sa.Column('describing_opinion_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_parenthetical_described_opinion_id'), 'search_parenthetical', ['described_opinion_id'], unique=False)
    op.create_index(op.f('ix_search_parenthetical_describing_opinion_id'), 'search_parenthetical', ['describing_opinion_id'], unique=False)
    op.create_index(op.f('ix_search_parenthetical_group_id'), 'search_parenthetical', ['group_id'], unique=False)
    op.create_index(op.f('ix_search_parenthetical_id'), 'search_parenthetical', ['id'], unique=False)
    op.create_table('search_docket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('referred_to_id', sa.Integer(), nullable=True),
    sa.Column('appeal_from_id', sa.String(length=50), nullable=True),
    sa.Column('docket_number', sa.Text(), nullable=True),
    sa.Column('case_name', sa.Text(), nullable=True),
    sa.Column('case_name_short', sa.Text(), nullable=True),
    sa.Column('case_name_full', sa.Text(), nullable=True),
    sa.Column('date_filed', sa.Date(), nullable=True),
    sa.Column('date_terminated', sa.Date(), nullable=True),
    sa.Column('date_argued', sa.Date(), nullable=True),
    sa.Column('date_reargued', sa.Date(), nullable=True),
    sa.Column('date_reargument_denied', sa.Date(), nullable=True),
    sa.Column('date_cert_granted', sa.Date(), nullable=True),
    sa.Column('date_cert_denied', sa.Date(), nullable=True),
    sa.Column('source', sa.SmallInteger(), nullable=True),
    sa.Column('pacer_case_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=75), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['appeal_from_id'], ['people_db_court.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['people_db_person.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['people_db_court.id'], ),
    sa.ForeignKeyConstraint(['referred_to_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_docket_assigned_to_id'), 'search_docket', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_search_docket_blocked'), 'search_docket', ['blocked'], unique=False)
    op.create_index(op.f('ix_search_docket_court_id'), 'search_docket', ['court_id'], unique=False)
    op.create_index(op.f('ix_search_docket_date_filed'), 'search_docket', ['date_filed'], unique=False)
    op.create_index(op.f('ix_search_docket_docket_number'), 'search_docket', ['docket_number'], unique=False)
    op.create_index(op.f('ix_search_docket_id'), 'search_docket', ['id'], unique=False)
    op.create_index(op.f('ix_search_docket_pacer_case_id'), 'search_docket', ['pacer_case_id'], unique=False)
    op.create_index(op.f('ix_search_docket_referred_to_id'), 'search_docket', ['referred_to_id'], unique=False)
    op.create_index(op.f('ix_search_docket_slug'), 'search_docket', ['slug'], unique=False)
    op.create_table('search_opinioncluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.Text(), nullable=True),
    sa.Column('case_name_short', sa.Text(), nullable=True),
    sa.Column('case_name_full', sa.Text(), nullable=True),
    sa.Column('date_filed', sa.Date(), nullable=True),
    sa.Column('date_argued', sa.Date(), nullable=True),
    sa.Column('date_reargued', sa.Date(), nullable=True),
    sa.Column('date_reargument_denied', sa.Date(), nullable=True),
    sa.Column('judges', sa.Text(), nullable=True),
    sa.Column('attorneys', sa.Text(), nullable=True),
    sa.Column('nature_of_suit', sa.Text(), nullable=True),
    sa.Column('posture', sa.Text(), nullable=True),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.Column('headnotes', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('scdb_id', sa.String(length=10), nullable=True),
    sa.Column('scdb_decision_direction', sa.String(length=50), nullable=True),
    sa.Column('scdb_votes_majority', sa.Integer(), nullable=True),
    sa.Column('scdb_votes_minority', sa.Integer(), nullable=True),
    sa.Column('precedential_status', sa.String(length=50), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=75), nullable=True),
    sa.ForeignKeyConstraint(['docket_id'], ['search_docket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_opinioncluster_blocked'), 'search_opinioncluster', ['blocked'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_citation_count'), 'search_opinioncluster', ['citation_count'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_date_filed'), 'search_opinioncluster', ['date_filed'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_docket_id'), 'search_opinioncluster', ['docket_id'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_id'), 'search_opinioncluster', ['id'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_precedential_status'), 'search_opinioncluster', ['precedential_status'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_scdb_id'), 'search_opinioncluster', ['scdb_id'], unique=False)
    op.create_index(op.f('ix_search_opinioncluster_slug'), 'search_opinioncluster', ['slug'], unique=False)
    op.drop_constraint('people_db_court_parent_court_id_fkey', 'people_db_court', type_='foreignkey')
    op.create_foreign_key(None, 'people_db_court', 'people_db_court', ['parent_court_id'], ['id'])
    # Skip setting person_id to NOT NULL - data contains NULLs
    # op.alter_column('people_db_education', 'person_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.drop_constraint('people_db_person_is_alias_of_id_fkey', 'people_db_person', type_='foreignkey')
    op.create_foreign_key(None, 'people_db_person', 'people_db_person', ['is_alias_of_id'], ['id'])
    op.drop_constraint('people_db_school_is_alias_of_id_fkey', 'people_db_school', type_='foreignkey')
    op.create_foreign_key(None, 'people_db_school', 'people_db_school', ['is_alias_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people_db_school', type_='foreignkey')
    op.create_foreign_key('people_db_school_is_alias_of_id_fkey', 'people_db_school', 'people_db_school', ['is_alias_of_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'people_db_person', type_='foreignkey')
    op.create_foreign_key('people_db_person_is_alias_of_id_fkey', 'people_db_person', 'people_db_person', ['is_alias_of_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('people_db_education', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'people_db_court', type_='foreignkey')
    op.create_foreign_key('people_db_court_parent_court_id_fkey', 'people_db_court', 'people_db_court', ['parent_court_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_search_opinioncluster_slug'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_scdb_id'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_precedential_status'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_id'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_docket_id'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_date_filed'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_citation_count'), table_name='search_opinioncluster')
    op.drop_index(op.f('ix_search_opinioncluster_blocked'), table_name='search_opinioncluster')
    op.drop_table('search_opinioncluster')
    op.drop_index(op.f('ix_search_docket_slug'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_referred_to_id'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_pacer_case_id'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_id'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_docket_number'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_date_filed'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_court_id'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_blocked'), table_name='search_docket')
    op.drop_index(op.f('ix_search_docket_assigned_to_id'), table_name='search_docket')
    op.drop_table('search_docket')
    op.drop_index(op.f('ix_search_parenthetical_id'), table_name='search_parenthetical')
    op.drop_index(op.f('ix_search_parenthetical_group_id'), table_name='search_parenthetical')
    op.drop_index(op.f('ix_search_parenthetical_describing_opinion_id'), table_name='search_parenthetical')
    op.drop_index(op.f('ix_search_parenthetical_described_opinion_id'), table_name='search_parenthetical')
    op.drop_table('search_parenthetical')
    op.drop_index(op.f('ix_search_opinionscited_id'), table_name='search_opinionscited')
    op.drop_index(op.f('ix_search_opinionscited_citing_opinion_id'), table_name='search_opinionscited')
    op.drop_index(op.f('ix_search_opinionscited_cited_opinion_id'), table_name='search_opinionscited')
    op.drop_table('search_opinionscited')
    # ### end Alembic commands ###

