"""Initial schema with correct types

Revision ID: dd4c263ddf70
Revises: 
Create Date: 2025-11-11 15:35:08.602208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4c263ddf70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_db_court',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('citation_string', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('jurisdiction', sa.String(length=3), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('parent_court_id', sa.String(length=15), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('pacer_court_id', sa.SmallInteger(), nullable=True),
    sa.Column('pacer_has_rss_feed', sa.Boolean(), nullable=True),
    sa.Column('pacer_rss_entry_types', sa.Text(), nullable=True),
    sa.Column('date_last_pacer_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fjc_court_id', sa.String(length=3), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.Column('has_opinion_scraper', sa.Boolean(), nullable=True),
    sa.Column('has_oral_argument_scraper', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_court_id'], ['people_db_court.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_court_id'), 'people_db_court', ['id'], unique=False)
    op.create_table('people_db_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_first', sa.String(length=50), nullable=True),
    sa.Column('name_middle', sa.String(length=50), nullable=True),
    sa.Column('name_last', sa.String(length=50), nullable=True),
    sa.Column('name_suffix', sa.String(length=5), nullable=True),
    sa.Column('date_dob', sa.Date(), nullable=True),
    sa.Column('date_dod', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('is_alias_of_id', sa.Integer(), nullable=True),
    sa.Column('fjc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['is_alias_of_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_person_date_dob'), 'people_db_person', ['date_dob'], unique=False)
    op.create_index(op.f('ix_people_db_person_fjc_id'), 'people_db_person', ['fjc_id'], unique=False)
    op.create_index(op.f('ix_people_db_person_id'), 'people_db_person', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_person_name_first'), 'people_db_person', ['name_first'], unique=False)
    op.create_index(op.f('ix_people_db_person_name_last'), 'people_db_person', ['name_last'], unique=False)
    op.create_table('people_db_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_alias_of_id', sa.Integer(), nullable=True),
    sa.Column('ein', sa.String(length=20), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_state', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['is_alias_of_id'], ['people_db_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_school_id'), 'people_db_school', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_school_name'), 'people_db_school', ['name'], unique=False)
    op.create_table('people_db_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('degree_level', sa.String(length=50), nullable=True),
    sa.Column('degree_detail', sa.String(length=100), nullable=True),
    sa.Column('degree_year', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people_db_person.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['people_db_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_education_degree_year'), 'people_db_education', ['degree_year'], unique=False)
    op.create_index(op.f('ix_people_db_education_id'), 'people_db_education', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_education_person_id'), 'people_db_education', ['person_id'], unique=False)
    op.create_index(op.f('ix_people_db_education_school_id'), 'people_db_education', ['school_id'], unique=False)
    op.create_table('people_db_politicalaffiliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('political_party', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_politicalaffiliation_date_start'), 'people_db_politicalaffiliation', ['date_start'], unique=False)
    op.create_index(op.f('ix_people_db_politicalaffiliation_id'), 'people_db_politicalaffiliation', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_politicalaffiliation_person_id'), 'people_db_politicalaffiliation', ['person_id'], unique=False)
    op.create_index(op.f('ix_people_db_politicalaffiliation_political_party'), 'people_db_politicalaffiliation', ['political_party'], unique=False)
    op.create_table('people_db_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.String(length=50), nullable=True),
    sa.Column('position_type', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_termination', sa.Date(), nullable=True),
    sa.Column('date_granularity_start', sa.String(length=10), nullable=True),
    sa.Column('date_granularity_termination', sa.String(length=10), nullable=True),
    sa.Column('how_selected', sa.String(length=50), nullable=True),
    sa.Column('nomination_process', sa.String(length=100), nullable=True),
    sa.Column('termination_reason', sa.String(length=100), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('successor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['people_db_court.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people_db_person.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['people_db_person.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['people_db_person.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_position_court_id'), 'people_db_position', ['court_id'], unique=False)
    op.create_index(op.f('ix_people_db_position_date_start'), 'people_db_position', ['date_start'], unique=False)
    op.create_index(op.f('ix_people_db_position_date_termination'), 'people_db_position', ['date_termination'], unique=False)
    op.create_index(op.f('ix_people_db_position_id'), 'people_db_position', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_position_person_id'), 'people_db_position', ['person_id'], unique=False)
    op.create_index(op.f('ix_people_db_position_position_type'), 'people_db_position', ['position_type'], unique=False)
    op.create_table('people_db_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_race_id'), 'people_db_race', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_race_person_id'), 'people_db_race', ['person_id'], unique=False)
    op.create_index(op.f('ix_people_db_race_race'), 'people_db_race', ['race'], unique=False)
    op.create_table('people_db_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_accessed', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people_db_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_db_source_id'), 'people_db_source', ['id'], unique=False)
    op.create_index(op.f('ix_people_db_source_person_id'), 'people_db_source', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_db_source_person_id'), table_name='people_db_source')
    op.drop_index(op.f('ix_people_db_source_id'), table_name='people_db_source')
    op.drop_table('people_db_source')
    op.drop_index(op.f('ix_people_db_race_race'), table_name='people_db_race')
    op.drop_index(op.f('ix_people_db_race_person_id'), table_name='people_db_race')
    op.drop_index(op.f('ix_people_db_race_id'), table_name='people_db_race')
    op.drop_table('people_db_race')
    op.drop_index(op.f('ix_people_db_position_position_type'), table_name='people_db_position')
    op.drop_index(op.f('ix_people_db_position_person_id'), table_name='people_db_position')
    op.drop_index(op.f('ix_people_db_position_id'), table_name='people_db_position')
    op.drop_index(op.f('ix_people_db_position_date_termination'), table_name='people_db_position')
    op.drop_index(op.f('ix_people_db_position_date_start'), table_name='people_db_position')
    op.drop_index(op.f('ix_people_db_position_court_id'), table_name='people_db_position')
    op.drop_table('people_db_position')
    op.drop_index(op.f('ix_people_db_politicalaffiliation_political_party'), table_name='people_db_politicalaffiliation')
    op.drop_index(op.f('ix_people_db_politicalaffiliation_person_id'), table_name='people_db_politicalaffiliation')
    op.drop_index(op.f('ix_people_db_politicalaffiliation_id'), table_name='people_db_politicalaffiliation')
    op.drop_index(op.f('ix_people_db_politicalaffiliation_date_start'), table_name='people_db_politicalaffiliation')
    op.drop_table('people_db_politicalaffiliation')
    op.drop_index(op.f('ix_people_db_education_school_id'), table_name='people_db_education')
    op.drop_index(op.f('ix_people_db_education_person_id'), table_name='people_db_education')
    op.drop_index(op.f('ix_people_db_education_id'), table_name='people_db_education')
    op.drop_index(op.f('ix_people_db_education_degree_year'), table_name='people_db_education')
    op.drop_table('people_db_education')
    op.drop_index(op.f('ix_people_db_school_name'), table_name='people_db_school')
    op.drop_index(op.f('ix_people_db_school_id'), table_name='people_db_school')
    op.drop_table('people_db_school')
    op.drop_index(op.f('ix_people_db_person_name_last'), table_name='people_db_person')
    op.drop_index(op.f('ix_people_db_person_name_first'), table_name='people_db_person')
    op.drop_index(op.f('ix_people_db_person_id'), table_name='people_db_person')
    op.drop_index(op.f('ix_people_db_person_fjc_id'), table_name='people_db_person')
    op.drop_index(op.f('ix_people_db_person_date_dob'), table_name='people_db_person')
    op.drop_table('people_db_person')
    op.drop_index(op.f('ix_people_db_court_id'), table_name='people_db_court')
    op.drop_table('people_db_court')
    # ### end Alembic commands ###

