"""Add missing OpinionCluster columns from CourtListener schema

Revision ID: e3ed3d3cc887
Revises: 62a6263eb9a0
Create Date: 2025-11-12 17:13:03.247663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3ed3d3cc887'
down_revision = '62a6263eb9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the missing OpinionCluster columns
    op.add_column('search_opinioncluster', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('date_modified', sa.Date(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('date_filed_is_approximate', sa.Boolean(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('date_blocked', sa.Date(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('headmatter', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('procedural_history', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('disposition', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('history', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('other_dates', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('cross_reference', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('correction', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('arguments', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('filepath_json_harvard', sa.Text(), nullable=True))
    op.add_column('search_opinioncluster', sa.Column('filepath_pdf_harvard', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the OpinionCluster columns we added
    op.drop_column('search_opinioncluster', 'filepath_pdf_harvard')
    op.drop_column('search_opinioncluster', 'filepath_json_harvard')
    op.drop_column('search_opinioncluster', 'arguments')
    op.drop_column('search_opinioncluster', 'correction')
    op.drop_column('search_opinioncluster', 'cross_reference')
    op.drop_column('search_opinioncluster', 'other_dates')
    op.drop_column('search_opinioncluster', 'history')
    op.drop_column('search_opinioncluster', 'disposition')
    op.drop_column('search_opinioncluster', 'procedural_history')
    op.drop_column('search_opinioncluster', 'headmatter')
    op.drop_column('search_opinioncluster', 'date_blocked')
    op.drop_column('search_opinioncluster', 'date_filed_is_approximate')
    op.drop_column('search_opinioncluster', 'date_modified')
    op.drop_column('search_opinioncluster', 'date_created')
    # ### end Alembic commands ###

